### ISSUE TITLE
`build.sh` contents?

### ISSUE THREAD

**Issue by 7yl4r** [tajmone/awesome-interactive-fiction#17]
I see `build.sh` referenced in `build-and-validate.sh` but it is not included in the repo.

I understand this may include sensitive info like github login credentials to deploy but can an example script be added?
Or else expand `CONTRIBUTING.md` to include more detailed build & deploy instructions.

**Comment by tajmone** [comment]
Hi @7yl4r!

> I see `build.sh` referenced in `build-and-validate.sh` but it is not included in the repo.

It's the [`docs_src/build.sh`][docs_src/build.sh] (i.e. not in the root folder but in the subfolder with the AsciiDoc sources).

There's also a [`docs_src/preview.sh`][docs_src/preview.sh] alternative script, for quickly testing changes without altering the published HTML doc and the root AsciiDoc version (coalesced single-document).


> I understand this may include sensitive info like github login credentials to deploy but can an example script be added?

No sensitive info — the scripts you see inside the repo are all there's to it. It's a fairly simple project, it builds the `docs/index.html` document which is served via GitHub Pages as a static website, and a "coalesced" single-document AsciiDoc version for the benefit of GitHub previewing.

The source files in `docs_Src/` are kept as multi-source split files just for convenience, instead of having to edit a huge single document contributors can focus just on the section they'd like to edit.

> Or else expand `CONTRIBUTING.md` to include more detailed build & deploy instructions.

I've kept all the specific instructions on how to build the sources in:

- [`docs_src/README.md`][docs_src/README.md]

I thought it made more sense to keep them next to the actual AsciiDoc sources, but you're right, I now I realize that I should make this point clearer in `CONTRIBUTING.md`. I'll update it as soon as possible.

Thanks for asking and pointing this out.



[docs_src/build.sh]: https://github.com/tajmone/awesome-interactive-fiction/blob/master/docs_src/build.sh "View source script"
[docs_src/preview.sh]: https://github.com/tajmone/awesome-interactive-fiction/blob/master/docs_src/preview.sh "View source script"
[docs_src/README.md]: https://github.com/tajmone/awesome-interactive-fiction/blob/master/docs_src/README.md

**Comment by tajmone** [comment]
I've now updated both the [`CONTRIBUTING.md`][CONTRIBUTING.md] and [`docs_src/README.md`][README.md] docs (commit 2d4cc0e), hoping to make it clear where to find the build instructions and info, and that the former only covers guidelines and code styles conventions.

Hopefully, the instructions in [`docs_src/README.md`][README.md] should be clear enough as they are. But if this is not case, please let me know where I could improve them. 



[CONTRIBUTING.md]: https://github.com/tajmone/awesome-interactive-fiction/blob/master/CONTRIBUTING.md
[README.md]: https://github.com/tajmone/awesome-interactive-fiction/blob/master/docs_src/README.md
