### ISSUE TITLE
Move IFM to Cross platform

### ISSUE THREAD

**Issue by DBX12** [tajmone/awesome-interactive-fiction#7]
Hi tajmone,
thank you for this list, its very helpful. What do you think about moving this mapping tool

> IFM (Interactive Fiction Mapper) — (1998–2014) Console/CMD executables available at IF Archive. IFM is a language for keeping track of gameplay progress, and a program for producing various different sorts of output using it, including automapping. See online documentation and IFWiki.

from MS Windows to Cross platform? The bitbucket repository contains information how to compile it for Linux. (Which "works on my machine" :tm: but better anecdotal proof than none ;) )

What do you think?
Cheers,
DBX12

**Comment by tajmone** [comment]
> What do you think?

Sounds good to me. Many resources I've taken them at face value from some basic description, not being able to test them all myself, so this type of category error is likely to be found elsewhere (also, some tools that once used to run on a single OS could probably work across other OSs today, thanks to new technologies).

When I find a time-slot I'll move the entry and update the description (I'll try to dig into the Linux version too, and provide more info).

**Comment by tajmone** [comment]
I've moved IFM to the ["Cross Platform" section] and tried to improve the presentation text so that it mentions that it runs on Linux too.

Not having had the chance to actually work with IFM myself, I've tried my best by quickly going through the official documentation to get a better picture of what IFM does.

@DBX12, could you please give me some feedback on the new text presenting IFM, and confirm whehter it's OK or if it needs revising?

["Cross Platform" section]: https://tajmone.github.io/awesome-interactive-fiction/#cross-platform-2

**Comment by DBX12** [comment]
Hey tajmone,
sorry for the late reply. Yes, the new text looks good :+1: 
The installation is not exactly trivial on Linux, but Glenn Hutchings (aka Bitbucket user zondo) did a great job documenting the process in the Bitbucket repo.
So all in all, I think we can be happy with the new text :)

**Comment by tajmone** [comment]
Thanks!
